### ISSUE TITLE
When specifying isoforms in genCov plots no longer align

### ISSUE THREAD

**Issue by zskidmor** [griffithlab/GenVisR#128]
the new feature in genCov is causing plots not to align, specifically the xlimits for the plots are NaN. This is related to the log transforms occuring. @ahwagner do you have any ideas?

**Comment by zskidmor** [comment]
For example running genCov while specifying the follwing:

x <- read.table(file='IKZF1.rdct.tsv', sep="\t", header=F)
## Load transcript meta data
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
txdb <- TxDb.Hsapiens.UCSC.hg19.knownGene
## Load genome
library(BSgenome.Hsapiens.UCSC.hg19)
genome <- BSgenome.Hsapiens.UCSC.hg19

gr <- GRanges(seqnames=c(chr7)), ranges=IRanges(start=c(50304124),end=c(50405101)))

genCov(x, txdb, gr, genome, isoformSel='uc003tow.4')

will reproduce the error

**Comment by ahwagner** [comment]
Fix for this is in progress on the [hotfix branch](https://github.com/griffithlab/GenVisR/tree/hotfix).
