### ISSUE TITLE
Get GenVisR vigette to work with the vignette() function

### ISSUE THREAD

**Issue by malachig** [griffithlab/GenVisR#171]
It should be possible to get the GenVisR vignette to show in the list of available vignettes when one does `vignette()` in an R session after loading the GenVisR library.

Then this will open the PDF: 
vignette("GenVisR")

**Comment by zskidmor** [comment]
I looked into this a little further, the following steps will solve this issue:
1. build source package (can be done via rstudio or devtools::build())
2. install source package (R CMD INSTALL GenVisR.tar.gz)

This will create a doc folder in the install location, running this will then display the vignette:
vignette("GenVisR_intro")

For some reason it appears that Rstudio/devtools does not create the doc folder automatically (there is probably a parameter somewhere). It does appear when installing from source.

Leaving this open for now while I verify and to remind myself that the vignette should probably be renamed from GenVisR_intro to GenvisR.
