### ISSUE TITLE
Coverage looks abnormal at exons when compressing space

### ISSUE THREAD

**Issue by zskidmor** [griffithlab/GenVisR#208]
running the following command will illustrate the abnormality:
```R
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
txdb <- TxDb.Hsapiens.UCSC.hg19.knownGene

# Load BSgenome
library(BSgenome.Hsapiens.UCSC.hg19)
genome <- BSgenome.Hsapiens.UCSC.hg19

# Define a region of interest 
gr <- GRanges(seqnames=c("chr10"), ranges=IRanges(start=c(89622195), 
end=c(89729532)), strand=strand(c("+")))

# Define preloaded coverage data as named list
data <- list("PTEN" = ptenCov)

# Call genCov
genCov(data, txdb, gr, genome, gene_labelTranscriptSize=2)
```
partial output of coverage_data lines (3161-3167), put a stop on line 186 of genCov
3161 25.90576 25.98117  37
3162 26.65981 26.73521  38
3163 27.41385 27.48926  40
3164 28.16790 28.24330  37
3165 28.92195 28.99735  34
3166 29.67599 29.75140  39
3167 30.43004 30.50544  43

given this is single base resolution we should have more entries than one for an integer with the compression.

**Comment by ahwagner** [comment]
Fixed! Somebody was using downsampled data...
