### ISSUE TITLE
Support for addtional file_types in waterfall plot

### ISSUE THREAD

**Issue by zskidmor** [griffithlab/GenVisR#26]
Currently only TGI annotation files and MAF version 2.4 are supported by the waterfall plot, It might be worthwhile to support additional file types (VCF, older MAF versions, etc.)

 This would mean adding code in the following functions:
hiearchial_remove_trv_type.R
mutation_heatmap.R
plot_heatmap.R

**Comment by zskidmor** [comment]
in a previous commit custom file types are now supported, i think this solves this issue

**Comment by kb472** [comment]
I'm not seeing any documentation on how I get waterfall plot from vcf file - can you give me some pointers ? Thanks

**Comment by zlskidmore** [comment]
see section 1.1.1 here: https://bioconductor.org/packages/release/bioc/vignettes/GenVisR/inst/doc/waterfall_introduction.html#loading-primary-input

you need to convert your vcf to a 3 column data frame and set the `fileType` and `variant_class_order` parameters

Unfortunately VCF format by itself is not strictly supported however it should be relatively painless to extract the columns from the VCF you need and supply the information to GenVisR
