### ISSUE TITLE
Any support/workaround for R/Bioconductor version 3.2?

### ISSUE THREAD

**Issue by keithcallenberg** [griffithlab/GenVisR#270]
The most typical use context for R and Bioconductor is probably personal systems that can spontaneously update to latest versions, but I'm sure there are at least a number of potential users that are reliant on system administrators and other dependencies that can't yet upgrade to 3.3. One reference point is that the latest version of [BioBuilds](https://github.com/lab7/biobuilds/blob/rel-2016.04/Release-Notes-2016.04.md#applications-in-biobuilds-201604) released in April is at 3.2.2. Is there any way to get GenVisR working on 3.2?

**Comment by zlskidmore** [comment]
@keithcallenberg, development has mainly occurred on R 3.3.0 and is the reason for this dependency however I see no real issues with lowering the R dependency. I've created a new branch called R_3.2.2_test for this purpose. The following workflow should work for you:

1. Install the bioconductor package dependencies located in the DESCRIPTION file under the IMPORTS section (I suspect you will have to use an older version of bioconductor for may of these packages, these are available here: (https://www.bioconductor.org/checkResults/3.1/bioc-20151009/#B)

2. Install GenVisR from the github repo (install devtools if it's not already installed), the CRAN dependencies should be installed automatically:
devtools::install_GitHub("griffithlab/GenVisR", ref="R_3.2.2_test")

I have tested this with R 3.2.4 and everything seems to work okay, If you run into problems let me know

**Comment by keithcallenberg** [comment]
I am running R 3.2.2. I got a warning that the MASS dependency did not install properly, but this is likely specific to my machine, and when I proceeded to load and test GenVisR, there were no issues. 

I tested it using this tutorial: https://www.biostars.org/p/196576/
