### ISSUE TITLE
"CoMut" style proportion of mutation types in waterfall()

### ISSUE THREAD

**Issue by Alanocallaghan** [griffithlab/GenVisR#279]
I think it would be useful to add (probably optional) proportions of mutation types to these plots, as seen in the bottom "subplot" of this CoMut plot: https://www.broadinstitute.org/blog/visualizing-cancer-genome

I have implemented this using the existing `trv_type` column in `data_frame` in `waterfall.R`, but in principle could process the nucleotide alteration data in MAF files to produce something more like the CoMut plot. This could be useful for visualising individuals' mutational profiles.
CoMut example: http://imgur.com/a/uDuAz

**Comment by Alanocallaghan** [comment]
I would note that using the same colour scheme for the clinical data plot and the mutational profile plot is completely absurd, but it's irrelevant for the example. If this is something you are interested in incorporating, I'd be happy to work it up more thoroughly and submit a pull request

**Comment by zlskidmore** [comment]
@Alanocallaghan Thanks for the suggestion! I should be able to work this in in the coming months.

 I would be happy to accept a pull request if you beat me to it and would like to contribute. I agree that we should use a different color scheme, the palettes for the existing trv_types are defined in waterfall_buildMain() we should probably use those.

**Comment by Alanocallaghan** [comment]
Hi Zach, I'll work that up in this case. I think it makes more sense to extract the palette code to a separate function than to duplicate those so I'll have a think and get working on it soon. Cheers

**Comment by Alanocallaghan** [comment]
I've got a working prototype of the simple version I described above. I realise that you have something very similar (TvTi) in this package already so I'll try to implement that as an option also, and then submit a PR

**Comment by zlskidmore** [comment]
Sounds good! Looking forward to seeing the new code

**Comment by Alanocallaghan** [comment]
Here are some examples, if you have any suggestions I'd be happy to work them in. http://imgur.com/a/kAIEk

Currently, the bottom plot is made using the non-subsetted data (just like the top part showing mutational burden), but it might also make sense to allow the user to toggle between only displaying the data plotted in the main heatmap and plotting all data, for both of these plots. All that needs to change is the input so it should be trivial.

**Comment by zlskidmore** [comment]
resolved by #283
