### ISSUE TITLE
theme_bw on mutation burden part of waterfall causes minor misalignment of samples

### ISSUE THREAD

**Issue by Alanocallaghan** [griffithlab/GenVisR#280]
Some part of theme_bw as used on the mutation burden plot (`waterfall_buildMutBuden_A.R` and `waterfall_buildMutBuden_B.R`) causes the x-axis to shift very slightly relative to the other plots (this becomes noticable when n > 100 and the plot is large). It would be optimal to use similar themes on each of the plots.

**Comment by Alanocallaghan** [comment]
My suggestion would be to define a theme close to theme_bw() but not use it in its entirety, eg:


    # Define Theme
    theme <- theme(axis.ticks.x = element_blank(),
                   axis.text.x = element_blank(),
                   axis.title.x = element_blank(),
                   legend.title = element_text(size=14),
                   axis.text.y = element_text(colour = "black"),
                   axis.title.y = element_text(colour = "black"),
                   panel.background = element_blank(),
                   panel.grid.major.y = element_line(colour = "grey80"),
                   panel.grid.minor.x = element_blank(),
                   panel.grid.major.x = element_blank(),
                   panel.border = element_rect(fill = NA)
            )

After all, users can alter this in any case by passing one in mutBurdenLayer

**Comment by zlskidmore** [comment]
Thanks for pointing this out! I'll look into replacing all the theme_bw() calls with what you suggest. shouldn't take long.

**Comment by Alanocallaghan** [comment]
Hi Zach, bit of a fudge here. The problem is actually related to the "synonymous"/"non-synonymous" legend on the mutation load top plot. Removing the legend causes the plot to shift slightly right! this is a difficult problem to account for as I'm not sure how ggplot2 adjusts for the presence/absence of a legend

**Comment by zlskidmore** [comment]
yeah, I use a trick suggested in the forums in waterfall_align() where all plots are converted to grob objects I then set the widths of all plots to be equal. It's expected that if in the grob list there are not an identical number of grobs to act on things go awry.

In your plots is everything mis-aligned or just the first/last bars.

**Comment by Alanocallaghan** [comment]
Yes I've looked through the waterfall_align code, it's unfortunate that the addition or removal of a legend causes ggplot objects to be removed. For now, a workaround (assuming one wants to remove the top legend) is to pass this via mutBurdenLayer:

    guides(fill = guide_legend(
            title = NULL,
            label = FALSE,
            override.aes = list(fill = "white")))

If I can find a way to ensure the plot doesn't shift if the legend is removed, I'll post it here
