### ISSUE TITLE
'rmvSilent=TRUE' Bug with custom file type

### ISSUE THREAD

**Issue by lavv2** [griffithlab/GenVisR#295]
Hi,

Using the last version available on Bioconductor, when I add the option `rmvSilent=TRUE` to the waterfall command, it returns the following error message:
```
Error in waterfall_hierarchyTRV(data_frame, fileType, variant_class_order) : 
  Detected an invalid mutation type, valid values for Custom are; ...

```
If I use the exact same waterfall command but without the 'rmvSilent=TRUE', it works.

NOTES:
* my command:
`waterfall(tumor.sup,fileType = "Custom",variant_class_order = most_deleterious,mainXlabel = TRUE,mainRecurCutoff = 0.5, rmvSilent = TRUE)`
* tested on custom and brcaMAF data formatted as 'sample\tgene\tvariant_class\tOther' using respectively the columns 'Tumor_Sample_Barcode', 'Hugo_Symbol', 'Variant_Classification', 'Variant_Type'
* I am using a custom fileType with custom variant classes.
* All my variant_class and variant_class-order elements match.

**Comment by zlskidmore** [comment]
@lavv2 I have discovered the issue, internally to remove silent mutations the function looks for synonymous or silent (case insensitive) and replaces them with NA. This ensures that when plotting the sample still maintains a column and NA values (in variant_class )are just not plotted. I have a simple patch to alleviate this issue however in the meantime adding NA to the "most_deleterious" vector you have will solve the issue.

```R
library(GenVisR)
tumor.sup <- brcaMAF[,c('Tumor_Sample_Barcode', 'Hugo_Symbol', 'Variant_Classification', 'Variant_Type')]
colnames(tumor.sup) <- c("sample", "gene", "variant_class", "Other")

most_deleterious <- c(as.character(unique(tumor.sup$variant_class)), NA)

waterfall(tumor.sup,fileType = "Custom",variant_class_order = most_deleterious,
          mainXlabel = TRUE,mainRecurCutoff = 0.5, rmvSilent = TRUE)
```

**Comment by lavv2** [comment]
Great, thanks !
