### ISSUE TITLE
How to retrieve mutation burden data from waterfall plot

### ISSUE THREAD

**Issue by shirleydaidai** [griffithlab/GenVisR#304]
Hello,
Is there a way to retrieve mutation burden data for each sample from the waterfall plot (top plot)?
Thanks
Shirley

**Comment by zlskidmore** [comment]
if you set the param data="out" it will provide a list of data frames corresponding to the underlying data.

**Comment by shirleydaidai** [comment]
Thanks for your reply.
As I can see from my "mutation_count" data.frame, "mutation_total" was calculated twice, one for "Synonymous" and one for "Non Synonymous" for the same sample. Should I summarize them together for the total count for that sample?

**Comment by zlskidmore** [comment]
yes, they were just split like that for plotting purposes. Combining them will give the total mutation count observed for that sample in the data provided.

**Comment by shirleydaidai** [comment]
Alright. Many thanks.
