### ISSUE TITLE
Make segment color in cnView configurable

### ISSUE THREAD

**Issue by lbeltrame** [griffithlab/GenVisR#307]
The green tint used when overlaying segments on the log2ratio / copy number data isn't too pretty to show in a publication. Instead of hardcoding, the `colour` option used in `cnView_buildMain` could get a parameter passed to it (`segmentColor`?). 

I can look into it, but I'd like a suggestion on the parameter name (API naming isn't my best).

**Comment by zlskidmore** [comment]
@lbeltrame `segementColor` sounds good to me!

You might be able to do this in a round about way by passing another geom_segment() layer through the plotLayer param. but that would be some work for the user so probably best just to make another param.
