### ISSUE TITLE
waterfall rmvSilent = TRUE do not remove Intron

### ISSUE THREAD

**Issue by apastore** [griffithlab/GenVisR#310]
Hi, which type of Variant_Classification are removed by rmvSilent = TRUE in waterfall plot?
I still have Intron, 5'UTR, 3'UTR variants. would be possible to configure the set of variable to remove?

also would be nice to have do not remove Silent mutations for a particular genes, let's say TERT promoter mutations should be there even and not removed by  rmvSilent.

Thanks!

**Comment by zlskidmore** [comment]
thanks for the suggestion @apastore, you are right that parameter only looks for silent mutations and removes those. this is referenced in #296. I think I am going to implement your suggestion and have the user to optionally decide what to remove. Can't say when this will be fully implemented. For the second part of your comment, selectively removing mutations for genes, implementing that might be overly complicated for the end user. In the next major release users will be able to access individual plots (including the subplots) and make alterations. I think that's the best way to go for that situation.
