### ISSUE TITLE
'length.out' must be a non-negative number In pie lolliplot

### ISSUE THREAD

**Issue by juanmas07** [griffithlab/GenVisR#315]
I'm trying to create a lolliplot with pie charts:

`plt2 <- lolliplot(sample.gr, features,ylab=gene_name,type="pie",legend=legends)
`

And I'm getting this:

> Error in seq.int(percent[i], percent[i + 1], length.out = n) : 
>   'length.out' must be a non-negative number

So the sample.gr contains:

> 
> GRanges object with 5 ranges and 6 metadata columns:
>           seqnames       ranges strand |    value1    value2    value3    value4
>              <Rle>    <IRanges>  <Rle> | <numeric> <numeric> <numeric> <numeric>
>    snp132     chr1 [ 132,  132]      * |        12         6        16         0
>    snp525     chr1 [ 525,  525]      * |         3         0         1         0
>    snp680     chr1 [ 680,  680]      * |         1         0         2         0
>   snp2270     chr1 [2270, 2270]      * |         0         0         0         0
>   snp2368     chr1 [2368, 2368]      * |         2         0         2         0
>                                 color      border
>                                <list> <character>
>    snp132 #DB7575,#FFD700,#95cf5d,...      gray30
>    snp525 #DB7575,#FFD700,#95cf5d,...      gray30
>    snp680 #DB7575,#FFD700,#95cf5d,...      gray30
>   snp2270 #DB7575,#FFD700,#95cf5d,...      gray30
>   snp2368 #DB7575,#FFD700,#95cf5d,...      gray30
>   -------
>   seqinfo: 1 sequence from an unspecified genome; no seqlengths

And the features are:

> GRanges object with 6 ranges and 1 metadata column:
>       seqnames       ranges strand |    fill
>          <Rle>    <IRanges>  <Rle> |  <list>
>   [1]     chr1 [   0,  244]      * | #b1ed95
>   [2]     chr1 [ 546,  664]      * | #b1ed95
>   [3]     chr1 [ 772, 1050]      * | #b1ed95
>   [4]     chr1 [1746, 1840]      * | #b1ed95
>   [5]     chr1 [2236, 2271]      * | #b1ed95
>   [6]     chr1 [2383, 2418]      * | #b1ed95
>   -------
>   seqinfo: 1 sequence from an unspecified genome; no seqlengths

All seems to be OK, don't understand where's the issue

**Comment by zlskidmore** [comment]
Hi @juanmas07, 

I think you might have been looking at the documentation from the trackview package for the lolliplot function. The GenVisR lolliplot does not take a granges object.

Zach
