### ISSUE TITLE
An Error occured durning installation 

### ISSUE THREAD

**Issue by yipukangda** [griffithlab/GenVisR#320]
hi,

An error 
```
Error : object ‘rbind.gtable’ is not exported by 'namespace:gridExtra'
ERROR: lazy loading failed for package ‘GenVisR’
```
occured after running follow command

```
source("https://bioconductor.org/biocLite.R")
biocLite("GenVisR")
```
I have tried installing 'gridExtra' but it still did not work.

The full error massage is below:
```
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.4 (BiocInstaller 1.24.0), R 3.3.1 (2016-06-21).
Installing package(s) ‘GenVisR’
trying URL 'https://bioconductor.org/packages/3.4/bioc/src/contrib/GenVisR_1.4.1.tar.gz'
Content type 'unknown' length 2991981 bytes (2.9 MB)
==================================================
downloaded 2.9 MB

* installing *source* package ‘GenVisR’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error : object ‘rbind.gtable’ is not exported by 'namespace:gridExtra'
ERROR: lazy loading failed for package ‘GenVisR’
* removing ‘/home/gfk006/software/R-3.3.1/library/GenVisR’

The downloaded source packages are in
	‘/tmp/RtmpC79lfl/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘GenVisR’ had non-zero exit status
```

**Comment by yipukangda** [comment]
GenVisR is installed using
```
devtools::install_github("griffithlab/GenVisR")
```
but I guess someone met same problem as me.

**Comment by zlskidmore** [comment]
Yeah, unfortunately there's not much I can do. There is an incompatibility with the new gridExtra when used with an older GenVisR. Bioconductor package versions are tied to R versions so even installing the latest GenVisR using bioconductor 3.4 isn't installing the latest GenVisR just the last one for R 3.3. There are a few options to get around this.

1. Don't install the latest version of gridExtra, make sure an earlier version is installed from the cran archives

2. Update to the latest GenVisR on bioconductor (this would mean updating R to the latest version)

3. Install via github to avoid being tied to a specific R version

Hopefully this helps, but it looks like you already used the 3rd solution. If you run into further issues please let me know. Closing for now
