### ISSUE TITLE
change in cnSpec with changes in screen size

### ISSUE THREAD

**Issue by rtpandey** [griffithlab/GenVisR#326]
Hello Zach
In using cnSpec, why do the plots change when the screen size is changed. I tried this hint.

    pdf(file = "plot.pdf", height = 8, width = 14)
    cnSpec(cndata,genome="hg19")
    genome specified is preloaded, retrieving data...
    dev.off
    Zooming in or out still changes the red and blue line positions. I am working with germline microarray data, so the gains/losses are very thin lines.. I am just curious about what causes this.

@rtpandey
rtpandey commented an hour ago

To answer my own question, maybe zooming out causes closely occurring thin lines to look like a visible thick line, and when I go in, they spread out and are too light to be visible?

**Comment by zlskidmore** [comment]
@rtpandey are you referring to zooming in and out using a viewer like adobe or preview or when changing the size of the graphics device in R?

Speaking from the experience of preview in mac, many times with small elements particularly skinny lines the viewer has trouble correctly rendering them for some reason. Perhaps exporting your .pdf to a high resolution image .png might help? I recall an issue with very small lines not showing up before, theres not much I can do on the GenVisR side, but if it is a major issue I suppose you could alter the data to add a flank to regions below a certain size essentially making the CN regions a minimum size for display purposes. You should probably be clear that's what you did though if writing methods.
