### ISSUE TITLE
Waterfall: define ratio synonymous/non-synonymous after set mutBurden 

### ISSUE THREAD

**Issue by Tato14** [griffithlab/GenVisR#327]
Hi! 
I am plotting the calculation of the mutation burden with the mutBurden variable but I don't know how to specify which proportion is a synonymous or non-synonymous variant. 

Should I use the mutBurdenLayer variable? How should I plot, for example 50% - 50% synonymous/non-synonymous?

Thanks!

**Comment by zlskidmore** [comment]
Hi @Tato14, 

I'm not sure this is possible in the current version, you could try passing in an additional layer to overwrite the previous one however the way it's set up i'm not sure it will work.

**Comment by Leo-1992** [comment]
Dear author
Could we realize the annovations of synonymous or non-synonymous variant as well as  mutation burden in current  version？

**Comment by pcw271** [comment]
Can I have the x axis group by the clinical info, like lineage and subtype for waterfall plot?

**Comment by zlskidmore** [comment]
grouping is not currently supported, you can define a custom order with` sampOrder`

**Comment by pcw271** [comment]
Hi, Zach,

It would achieve the desired plotting.
Thank you so much!

Kate

**Comment by pcw271** [comment]
Hi Zach, I would like to modify to size of the legend for clinical data, I
try to use plotDLayer to add the ggplot list, but it seem not work.
Would you give me an example for that?
Thank you.

Kate
