### ISSUE TITLE
Sub-Plot Aesthetics

### ISSUE THREAD

**Issue by krissaMAC** [griffithlab/GenVisR#329]
Hi.
I would like to adjust the size of the different subplots within the waterfall function.
For example I would like to reduce the size of the mutation frequency plot and increase the size the clinical data plot. How do you do that? I tested section_heights = c(1, 1) but it does not work.
Also, it is possible to remove the top sub-panel "mutations per Mb". I tried plotMutBurden = FALSE but it removes all the plots.

Finally, is is possible to retrieve the individual plot ggplot2 so that I can re-plot with a another plot?

Thank you!!!

**Comment by zlskidmore** [comment]
Hi @krissaMAC 

if you have clinical data you should `section_heights` should have three values for the clinical, main, and mutation burden plot. This is true even if plotMutBurden=FALSE, the function has a nasty hack in it where even if you set plotMutBurden=FALSE the value for the plot still exists but is just blank. I'm nor sure why plotMutBurden=FALSE would eliminate all plots, can you send me the output of sessionInfo() and your command?

It is possible to retrieve individual plots just add the param out="grob", this will output a list of graphical objects that you can either manipulate or draw with `grid.draw()`

**Comment by krissaMAC** [comment]
Thank you for your note! I was able to adjust the subplot dimension by using (for example => section_heights = c(1, 1, 1)). 
I used the parameter out="grob" but I am not sure how to access the list of graphical objects.

**Comment by zlskidmore** [comment]
if you run `tmp <- waterfall(brcaMAF, mainRecurCutoff = .3, out="grob")`

you can view/access individual element's like this

`grid::grid.draw(tmp$grobs[[5]])`

This resource goes into detail a bit more about 2/3 the way down: http://genviz.org/module%203/0003/03/01/tvti_GenVisR/

**Comment by krissaMAC** [comment]
Thanks for the awesome advice! I run the suggested example and works fine.
Where can i get the clinical data?

But when I run the code bellow and use out= "grob", tm is null. 
However if I save it to pdf it works fine. I am ploting frequency, main and clinical plots.

tm <- waterfall(table, fileType="Custom", variant_class_order=variant_class_order, mainXlabel=TRUE,
               clinData = clinical_info.comb, clinVarCol = c(group1= "blue4", group2= "red", high = "hotpink2", 
                                                             low ="orange", "0-30"= "red", "30-60"= "lightblue", "60-90"= "steelblue1", "90-120"= "blue", "120-150"= "darkblue",
                                                             YES= "lightgreen", NO= "darkgreen", "< 1 cm residual"= "pink", "unknown"= "grey","none"="blue","sub-optimal"="purple"), 
               clinLegCol = 5, clinVarOrder = c("group1", "group2", "high", "low", "0-30", "30-60", "60-90", "90-120", "120-150", "YES","NO","< 1 cm residual", "unknown","none","sub-optimal"),
               sampOrder=new_samp_order.c, out="grob")

**Comment by zlskidmore** [comment]
Hi @krissaMAC,

This actually was a bug where you could not output differing object, (grob, data) if clinical data was supplied. I've patched the version on github I'll update the version on bioconductor later this week. If you want to try the patched version now install GenVisR from github with the devtools package. `devtools:install_github("griffithlab/GenVisR")` The version number should be 1.13.1

**Comment by zlskidmore** [comment]
feel free to reopen this issue if you still have a problem
