### ISSUE TITLE
Keep genes without mutations using waterfall

### ISSUE THREAD

**Issue by Tato14** [griffithlab/GenVisR#340]
Hi!

I am working with targeted panel sequencing and I would like to know if I could keep all the genes from the targeted panel, although some of them does not have any mutation reported. I tried to add empty rows with the gene names in the working data frame but does not solve the problem.

Any suggestions?
Thanks!

**Comment by zlskidmore** [comment]
Hi @Tato14 

This is not currently something GenVisR can do, but it shouldn't be hard to implement. I should have a patch as soon as today, but more realistically tuesday or wednesday CST

**Comment by malachig** [comment]
Thanks for the suggestion @Tato14.   This is a good use case that probably quite a few people would find useful.

**Comment by Tato14** [comment]
Happy to help @malachig :)

**Comment by Tato14** [comment]
It works great! Thanks @zlskidmore !

**Comment by zlskidmore** [comment]
Awesome!, if you run into any issues feel free to reopen!
