### ISSUE TITLE
Remove gene proportion barplot

### ISSUE THREAD

**Issue by Tato14** [griffithlab/GenVisR#341]
Hi! 
Is there any argument to remove the left barplot (%Mutation)?

Thanks!

**Comment by zlskidmore** [comment]
Hi @Tato14 

If using the newer S4 style `Waterfall()` function you can set the `plotB` param to NULL and it will omit the plot

here's an example using some test data

```R
library(data.table)
library(GenVisR)
test <- data.table("sample"=rep("test1", 5), "gene"=c(rep("egfr", 2), rep("rb1", 3)),
                                          "mutation"=c(rep("missense", 2), rep("nonsense", 2), "frameshift")))

out <- Waterfall(test, plotB=NULL)

drawPlot(out)
```
