### ISSUE TITLE
change the linespace in cnSpec() 

### ISSUE THREAD

**Issue by wangfan860** [griffithlab/GenVisR#344]
Hi,

I'm using the cnSpec function, which is amazing. However, sometimes when I need to plot a heatmap for like 100 samples, it's really hard to see the color because the linespace is way too big. Do you know how to change the size of space?

Thanks
Fan
[Rplot01.pdf](https://github.com/griffithlab/GenVisR/files/2307994/Rplot01.pdf)

**Comment by zlskidmore** [comment]
Hi @wangfan860,

Are you referring to the spacing of the faceted plots between samples? if so something like this should work

```r
library(GenVisR)
library(ggplot2)
new_theme <- theme(panel.spacing.y = unit(0, "lines"))
cnSpec(LucCNseg, genome="hg19", plotLayer = new_theme)
```

pretty much anything in these plots can be altered by passing additional ggplot2 layers, let me know if this is what you were referring to or if I misunderstood.

**Comment by wangfan860** [comment]
Thank you so much! That's exactly what I need. How about the border color and thickness of each row? Thanks again!

**Comment by wangfan860** [comment]
I think I figured out the border things. Now I want to add geom_vline to the layer as well? How can I do that? I tried `plotLayer = new_theme +geom_vline(xintercept = c(500000, 1000000), colour="seagreen4", size=0.5, linetype=2)` but I got Error: Don't know how to add RHS to a theme object
