### ISSUE TITLE
package or namespace load failed for ‘WGCNA’ in rbind

### ISSUE THREAD

**Issue by alopehba** [griffithlab/GenVisR#348]
when I tried to using the package library(WGCNA) the Error shows:

> library(WGCNA)
Error: package or namespace load failed for ‘WGCNA’ in rbind(info, getNamespaceInfo(env, "S3methods")):
 number of columns of matrices must match (see arg 2)

I don't know what that means and how to do~~~~~`
Can anyone help me?
Thanks

**Comment by zlskidmore** [comment]
I don't think this is a problem with GenVisR, I am able to load GenVisR and WGCNA without issue. But looking at the error it appears that there is a namespace collision between WGCNA and another package.

You could try loading WGCNA first and then additional packages to determine which package is causing the issue. Alternatively you might be able to get away with calling the function you want to use explicitly something like `package::function()` i.e. reshape2::melt() for example

I'm going to close this issue for now but if you think genvisr is causing the problem please re-open
