### ISSUE TITLE
cnFreq y axis scale

### ISSUE THREAD

**Issue by cgrisdale** [griffithlab/GenVisR#353]
Hi,

When using cnFreq the plot often has a lot of white space above and below the max/min y-values (see attachment), which squishes the actual data. Is there a way to set the axis limits or some other parameter that will help minimize this blank area at the top and bottom of the plot?

Thanks,
Cam
![screenshot from 2019-01-31 15-46-35](https://user-images.githubusercontent.com/3093548/52093322-98ffa880-256f-11e9-95bc-ea34fa62457f.png)

**Comment by zlskidmore** [comment]
The y-limits are set automatically based on the data, I suspect you have a very small segment that is hard to see on the plot. At any rate you can adda ggplot layer to control the ylim, for example:

```r
library(GenVisR)
library(ggplot2)
layer <- ylim(c(-5, 5))
cnFreq(LucCNseg, plotLayer = layer)
```
