### ISSUE TITLE
Installation issue in AWS jupyter notebook instance

### ISSUE THREAD

**Issue by sharmi298** [griffithlab/GenVisR#361]
**During installation I get the following message and shows 'package not found error' when I use the library function** 

**R version used: 3.6.0**

Bioconductor version 3.9 (BiocManager 1.30.4), R 3.6.0 (2019-04-26)
Installing package(s) 'GenVisR'
also installing the dependencies ‘vctrs’, ‘blob’, ‘GenomicAlignments’, ‘DelayedArray’, ‘RSQLite’, ‘XVector’, ‘rtracklayer’, ‘BiocParallel’, ‘Rhtslib’, ‘SummarizedExperiment’, ‘AnnotationDbi’, ‘biomaRt’, ‘Biostrings’, ‘GenomicFeatures’, ‘GenomicRanges’, ‘IRanges’, ‘Rsamtools’, ‘BSgenome’, ‘GenomeInfoDb’, ‘VariantAnnotation’

Warning message in install.packages(pkgs = doing, lib = lib, repos = repos, ...):
“installation of package ‘Rhtslib’ had non-zero exit status”Warning message in install.packages(pkgs = doing, lib = lib, repos = repos, ...):
“installation of package ‘IRanges’ had non-zero exit status”Warning message in install.packages(pkgs = doing, lib = lib, repos = repos, ...):
“installation of package ‘DelayedArray’ had non-zero exit status”Warning message in install.packages(pkgs = doing, lib = lib, repos = repos, ...):
“installation of package ‘XVector’ had non-zero exit status”Warning message in install.packages(pkgs = doing, lib = lib, repos = repos, ...):
“installation of package ‘GenomeInfoDb’ had non-zero exit status”Warning message in install.packages(pkgs = doing, lib = lib, repos = repos, ...):
“installation of package ‘Rsamtools’ had non-zero exit status”Warning message in install.packages(pkgs = doing, lib = lib, repos = repos, ...):
“installation of package ‘GenomicAlignments’ had non-zero exit status”Warning message in install.packages(pkgs = doing, lib = lib, repos = repos, ...):
“installation of package ‘rtracklayer’ had non-zero exit status”Warning message in install.packages(pkgs = doing, lib = lib, repos = repos, ...):
“installation of package ‘GenomicFeatures’ had non-zero exit status”Warning message in install.packages(pkgs = doing, lib = lib, repos = repos, ...):
“installation of package ‘BSgenome’ had non-zero exit status”Warning message in install.packages(pkgs = doing, lib = lib, repos = repos, ...):
“installation of package ‘VariantAnnotation’ had non-zero exit status”Warning message in install.packages(pkgs = doing, lib = lib, repos = repos, ...):
“installation of package ‘GenVisR’ had non-zero exit status”Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Update old packages: 'askpass', 'boot', 'callr', 'caret', 'clipr', 'cluster',
  'curl', 'dbplyr', 'digest', 'dplyr', 'evaluate', 'foreach', 'formatR', 'fs',
  'ggplot2', 'glmnet', 'gower', 'haven', 'hexbin', 'hms', 'ipred', 'IRkernel',
  'iterators', 'knitr', 'markdown', 'MASS', 'mime', 'nlme', 'numDeriv',
  'openssl', 'pillar', 'processx', 'progress', 'quantmod', 'Rcpp', 'recipes',
  'repr', 'reprex', 'reticulate', 'rmarkdown', 'rvest', 'tibble', 'tinytex',
  'xfun', 'xml2', 'zoo'

**Comment by zlskidmore** [comment]
is this the full error message. I don't think GenVisR specifically is the issue but rather it's one of GenVisRs dependencies. I suspect one of these dependencies requires some system dependencies and the errors are propagating based on these missing system dependencies.

Can you try and install GenomicFeatures from Bioconductor that should fail based on the error messages above. Essentially this will have to be traced back to which underlying package/s GenVisR uses are causing the issue.

**Comment by sselvara-nmdp** [comment]
Hi Zachary,

Yes, the GenomicFeatures package failed as well. I think it's something to do with the 'Rhtslib' package. The Rhtslib package is not getting installed in the AWS environment.

If you have any idea regarding this issue, please get back to me as it will be very useful for my project.

________________________________

**Comment by zlskidmore** [comment]
are you running ubuntu? Rhtslib is the R implementation of the htslib library. Tthese are the system packages needed to get htslib to work on a vanilla ubuntu instance, if you apt-get install these in the linux terminal it might help things

```
apt-get update -y && apt-get install -y \
    bzip2 \
    build-essential \
    zlib1g-dev \
    libncurses5-dev \
    libncursesw5-dev \
    libnss-sss \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
```

**Comment by sselvara-nmdp** [comment]
I am running it on the AWS Sagemaker Jupyter notebook instance. I am very new so I am facing this difficulty. Not sure how I could install htslib in AWS.
________________________________

**Comment by zlskidmore** [comment]
I'm not super familiar with sagemaker, but you'll need to install those unix packages above to get this to work I think. I would assume sagemaker is running on a unix distribution so if you can get to a command line running apt-get install should be sufficient to get those packages

**Comment by sharmi298** [comment]
Thank you for the quick reply! Will try to work it out
