### ISSUE TITLE
waterfall() gives the error 

### ISSUE THREAD

**Issue by xiw588** [griffithlab/GenVisR#362]
I tried to run the waterfall function but got the error message of the following. 
Can anyone help me with this? 
Thank  you. 

Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto),  : 
  VECTOR_ELT() can only be applied to a 'list', not a 'NULL'
In addition: Warning message:
In waterfall_select_palette(file_type = file_type, custom_palette = plot_palette) :
  Defining a palette in mainPalette is recommended when file_type is set to "Custom", defaulting to a predefined palette with 20 levels

**Comment by zlskidmore** [comment]
I don't think this error is related to genvisr but rather R and or Rstudio itself based on a quick google search. Some have suggested restarting R has helped. If that doesn't work try outputting a grob object and drawing it explicitly, i.e.:

```R
tmp <- waterfall(brcaMAF, plotGenes=c("PIK3CA", "TP53", "USH2A", "MLL3", "BRCA1"), out="grob")
grid::grid.draw(tmp)
```

**Comment by xiw588** [comment]
Thank you very much! I tried and it worked!!
