### ISSUE TITLE
How to add results based on q-values for waterfall()

### ISSUE THREAD

**Issue by xiw588** [griffithlab/GenVisR#364]
Hi, I want to add a column of results for each gene based on q-values. Do you know how to do that with waterfall()?

Thank you.

**Comment by zlskidmore** [comment]
So you want an extra sub-plot? Currently that is unsupported, the best way to go around doing that would be to clone the repo and repurpose/change the code for the existing gene subplot or to output the plot as a grob `out="grob"` and modify the grob adding in your own plot. I wrote a tutorial on how to do this gennerally here https://genviz.org/module-07-appendix/0007/01/01/advancedggplot2/ however I would consider it an advanced topic
