### ISSUE TITLE
Error in geneViz_formatUTR when no UTRs

### ISSUE THREAD

**Issue by adam-cornwell** [griffithlab/GenVisR#386]
GenVisR 1.28.0
geneViz_extrUTR returns NA when there are no UTRs, but geneViz_formatUTR checks for NULL and not NA. Results in an error from a later call to a BioStrings function. Adding a check for NA in geneViz_formatUTR on the return value from geneViz_extrUTR fixes it.

**Comment by joegage** [comment]
I have a fork of this repo that fixes this issue - feel free to use:
https://github.com/joegage/GenVisR/blob/master/R/geneViz_formatUTR.R

I submitted a pull request, but there are pull requests still pending from 2016 so I'm not confident it will get fixed in this original repo.
