### ISSUE TITLE
FField dependency is deprecated

### ISSUE THREAD

**Issue by csmatyi** [griffithlab/GenVisR#389]
According to the list of dependencies, GenVisR uses FField. However, FField has been removed from CRAN and also failed checks. That is why for me GenVisR does not load and I am unable to use it.

**Comment by mheskett** [comment]
Yes just wanted to second this. I can't install GenVisR because of this message:

Warning: dependency ‘FField’ is not available

**Comment by zlskidmore** [comment]
this should be solved now, please re-open if not. you should be able to install directly from github or from bioc-devel branch once the nightly builds run
