### ISSUE TITLE
install GenVisr

### ISSUE THREAD

**Issue by kellyduarte** [griffithlab/GenVisR#390]
I can't able to install GenVisR, I've been trying for a few weeks with different versions of R and bioconductor, but it doesn't work, I would like to know if there was any update during this period that could have caused this problem?

**Comment by zlskidmore** [comment]
The FFIELD package was deprecated, I pushed a fix maybe a month ago, installing either from github or the bioconductor devel repo should work. Please try that and let me know if you still have issues
