### ISSUE TITLE
rename mutSpec function?

### ISSUE THREAD

**Issue by obigriffith** [griffithlab/GenVisR#94]
The mutation landscape function is currently named mutSpec. This could be confusing as it makes me think of mutation spectrum which this plot is not and for which we kind of have another function (TvTi).

**Comment by zskidmor** [comment]
Easy fix, any thoughts on the new name? perhaps one of these:

waterfall
mutSum (i.e. mutation summary)
sampView

**Comment by obigriffith** [comment]
I like waterfall.

On 8/22/15 10:49 PM, Zachary Skidmore wrote:
>
> Easy fix, any thoughts on the new name? perhaps one of these:
>
> waterfall
> mutSum (i.e. mutation summary)
> sampView
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/griffithlab/GenVisR/issues/94#issuecomment-133778535>.
>

-- 
Obi L. Griffith, PhD
Assistant Professor of Medicine, Division of Oncology
Assistant Director, McDonnell Genome Institute
Washington University School of Medicine
Campus Box 8501
4444 Forest Park Ave
St. Louis, MO, 63108
Phone: 314-747-9248
www.obigriffith.org



____
This email message is a private communication. The information transmitted, including attachments, is intended only for the person or entity to which it is addressed and may contain confidential, privileged, and/or proprietary material. Any review, duplication, retransmission, distribution, or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is unauthorized by the sender and is prohibited. If you have received this message in error, please contact the sender immediately by return email and delete the original message from all computer systems. Thank you.

**Comment by ahwagner** [comment]
I also like waterfall.

> On Aug 23, 2015, at 6:16 PM, Obi Griffith <notifications@github.com> wrote:
> 
> I like waterfall.
> 
> On 8/22/15 10:49 PM, Zachary Skidmore wrote:
> >
> > Easy fix, any thoughts on the new name? perhaps one of these:
> >
> > waterfall
> > mutSum (i.e. mutation summary)
> > sampView
> >
> > —
> > Reply to this email directly or view it on GitHub 
> > <https://github.com/griffithlab/GenVisR/issues/94#issuecomment-133778535>.
> >
> 
> -- 
> Obi L. Griffith, PhD
> Assistant Professor of Medicine, Division of Oncology
> Assistant Director, McDonnell Genome Institute
> Washington University School of Medicine
> Campus Box 8501
> 4444 Forest Park Ave
> St. Louis, MO, 63108
> Phone: 314-747-9248
> www.obigriffith.org
> 
> 
> 
> ____
> This email message is a private communication. The information transmitted, including attachments, is intended only for the person or entity to which it is addressed and may contain confidential, privileged, and/or proprietary material. Any review, duplication, retransmission, distribution, or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is unauthorized by the sender and is prohibited. If you have received this message in error, please contact the sender immediately by return email and delete the original message from all computer systems. Thank you.
> —
> Reply to this email directly or view it on GitHub <https://github.com/griffithlab/GenVisR/issues/94#issuecomment-133955891>.
> 



____
This email message is a private communication. The information transmitted, including attachments, is intended only for the person or entity to which it is addressed and may contain confidential, privileged, and/or proprietary material. Any review, duplication, retransmission, distribution, or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is unauthorized by the sender and is prohibited. If you have received this message in error, please contact the sender immediately by return email and delete the original message from all computer systems. Thank you.
