### ISSUE TITLE
mutSpec

### ISSUE THREAD

**Issue by rlesurf** [griffithlab/GenVisR#96]
When plotting clinical colors, it's currently difficult to differentiate between variables. For example, if I wanted ER status to be (positive=blue) and HER2 status to be (positive=red), I'd have to rename the variable values to something like HER2_positive, ER_positive, HER2_negative, etc. An alternative solution would be for the user to input a clinical data frame of colors (rather than variable values).

After opening a PDF graphics device, calling mutSpec multiple times only produces a single page of a plot. I'm guessing the layers from different mutSpec calls are getting put on top of each other.

You may want to rename the mutRecur.layers and main.layers. When I was trying to add ggtitle as a layer to the entire plot, I assumed it would be added to main.layers. But adding it to main.layers plotted nothing (ggtitle gets overridden internally there).

When drop_mutation=T, the mutation type colors can change depending on which types are present for a given set of samples. I think it would make more sense to have a static set of default colors that the user can alter manually.

**Comment by rlesurf** [comment]
Also, even with main.grid=T, there's no outer boundary lines around the middle section of the plot. Actually, there is a line on the left side, but none on the top, bottom, or right side.

**Comment by zskidmor** [comment]
moving this to phase 2

**Comment by zlskidmore** [comment]
Resolved in the new version I think
